stages:
  - build
  - deploy

compile:
  image: ubuntu:20.04
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    CXX: /usr/bin/g++-10
  script:
    - apt update && apt install -y libglfw3-dev libglew-dev cmake g++-10 git python3-dev
    - cmake .
    - make -j$(nproc)

# Trigger simulator update in spatzenhirn/ansible-server
deploy:
  only:
    - master
  image: curlimages/curl
  stage: deploy
  script:
    - curl --request POST --form "token=$ANSIBLE_TRIGGER_TOKEN" --form "ref=master" --form "variables[UPDATE_SIMULATOR]=true" https://git.spatz.wtf/api/v4/projects/265/trigger/pipeline
