stages:
  - build
  - deploy

compile:
  tags:
    - compile
  stage: build
  script:
    - cmake .
    - make -j8
  artifacts:
    paths:
      - lib
      - SpatzSim
      - models
      - shaders
    when: on_success
    expire_in: 1 hrs

# Trigger simulator update in spatzenhirn/ansible-server
deploy:
  only:
    - master
  stage: deploy
  script:
    - curl --request POST --form "token=$ANSIBLE_TRIGGER_TOKEN" --form "ref=master" --form "variables[UPDATE_SIMULATOR]=true" https://git.spatz.wtf/api/v4/projects/265/trigger/pipeline

