stages:
  - build
  - test
  - deploy

compile:
  tags:
    - compile
  stage: build
  script:
    - cmake .
    - make -j8
  artifacts:
    paths:
      - lib
      - SpatzSim
      - models
      - shaders
    when: on_success
    expire_in: 1 hrs

static_analysis_MR:
  allow_failure: true
  tags:
    - static-analysis
  stage: test
  only:
    - merge_requests
  script:
    - cmake .
    - make clean
    - scan-build -plist --intercept-first -o analyzer_reports make -j$(nproc)
    - sonar-scanner -Dsonar.projectVersion=$CI_COMMIT_SHA -Dsonar.branch.name=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.branch.target=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

static_analysis:
  allow_failure: true
  tags:
    - static-analysis
  stage: test
  only:
    - master
  script:
    - cmake .
    - make clean
    - scan-build -plist --intercept-first -o analyzer_reports make -j$(nproc)
    - sonar-scanner -Dsonar.projectVersion=$CI_COMMIT_SHA -Dsonar.branch.name=$CI_COMMIT_REF_NAME

# Trigger simulator update in spatzenhirn/ansible-server
deploy:
  only:
    - master
  stage: deploy
  variables:
    UPDATE_SIMULATOR: "true"
  trigger:
    project: spatzenhirn/ansible-server
