#!/bin/bash

SANDBOX_PATH="$HOME/sandboxes/CaroloSandbox"
ADTF_PATH="$SANDBOX_PATH/2019"
ADTF_BIN="/opt/adtf/bin/adtf_devenv"

FREEDRIVE_PROJECT_PATH="$ADTF_PATH/ADTF_Projekte/simulator_rundkurs/config/system.xml"
OBSTACLE_PROJECT_PATH="$ADTF_PATH/ADTF_Projekte/simulator_hindernis/config/system.xml"

if [ "$2" == "obstacle" ]
then
    PROJECT_PATH="$OBSTACLE_PROJECT_PATH"
else
    PROJECT_PATH="$FREEDRIVE_PROJECT_PATH"
fi

function on_exit {

    RC=$?

    echo $(jobs -p)
    pkill -TERM -P $(jobs -p)

    echo ""
    echo "[STEP] Finished with status code $RC"

    exit $RC
}

trap on_exit EXIT

set -e

echo "[STEP] Building vehicle software:"
echo ""

cd $ADTF_PATH
make

cd $SANDBOX_PATH
timeout -k 2m -s "TERM" --preserve-status 2m \
    ./current_adtf_devenv \
        -globals=current_sandbox.xml \
        -config="$PROJECT_PATH" \
        -run &

Simulator $1 &

wait -n
