name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies via APT
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libglfw3-dev libglew-dev
          version: 1.0
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --parallel $(nproc)
